"""add last_contacted_at to leads

Revision ID: 20a5139f0536
Revises: 3587c1f1c025
Create Date: 2026-03-06 20:08:31.311128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a5139f0536'
down_revision: Union[str, Sequence[str], None] = '3587c1f1c025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('last_contacted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'last_contacted_at')
    # ### end Alembic commands ###
