"""add lead stage field

Revision ID: 377ca00bb6be
Revises: 8df74727bd59
Create Date: 2026-03-11 11:44:00.815156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377ca00bb6be'
down_revision: Union[str, Sequence[str], None] = '8df74727bd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('stage', sa.String(), nullable=True))
    op.execute("UPDATE leads SET stage = 'new' WHERE stage IS NULL")
    op.alter_column('leads', 'stage', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'stage')
    # ### end Alembic commands ###
