"""remove stage

Revision ID: a30e21f67350
Revises: 377ca00bb6be
Create Date: 2026-03-11 12:17:41.691834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30e21f67350'
down_revision: Union[str, Sequence[str], None] = '377ca00bb6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'stage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('stage', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
