"""add trade_in to leads

Revision ID: b9c1a01131a2
Revises: 6eb2b1cd0f04
Create Date: 2026-04-13 23:18:13.172670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c1a01131a2'
down_revision: Union[str, Sequence[str], None] = '6eb2b1cd0f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('trade_in', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'trade_in')
    # ### end Alembic commands ###
